### ISSUE TITLE
Whether jit will affect the collection of path constraints

### ISSUE THREAD

**Issue by publishAE** [tudo-aqua/gdart-svcomp#1]
Hello, I'm very interested in your project, but I don't know much about JVM. Here's a question: will the JIT(Just in time compilation) affect the collection of path constraints by _SPouT_? 

As far as I know, the JIT identifies areas where the code can be optimized and compiles them to target machine code. A combination of bytecode and compiled code snippets provide the optimum way to execute the class files. 
And _SPouT_ is operated after each bytecode instruction to collect the path constraints of the program. So how to collect the path constraints of the compiled code part？

More specifically, for the following example code, according to my understanding, if we symbolize the variable `count` and pass it into the method `add(int count, int cp)`. As the method `add` is called a certain number of times, this method will be JIT compiled into the target machine code, and the JVM will directly execute this machine code. 
```
public static void main(String[] args) {
    int count;
    int a = 0;
    count = Verifier.nondetInt();
    while (a < 1000000) {
        add(count, a);
        a++;
    }
}

public static void add(int count, int cp){
    if(count < cp){

    }
}
```
In practice, I found that _SPouT_ can collect path constraints completely. I can't figure out how SPouT can collect complete path constraints only by modifying the interpreter in Espresso. After JIT compiles the method `add` into the target machine code, SPouT  should not be able to track symbolic variables in this machine code

I'm not sure it's my misunderstanding of the implementation in Espresso or SPouT  that leads to this view.

Hope for your answer!

**Comment by mmuesly** [comment]
Hi,

Espresso is a Java program running on top of the GraalVM. If the JIT compiler in the GraalVM kicks in, it compiles the Espresso code into the optimized form. So the complete Java interpreter is compiled by JIT. This maintains the path collection. Further optimizations are part of the truffel framework and managed by the GraalVM.

We do not controll the JIT compiler from SPouT. It is all managed by the GraalVM. If you want to learn all the details, you will have to contact the GraalVM team: https://www.graalvm.org/community/.

I am sorry that I cannot answer your question in more detail.

**Comment by publishAE** [comment]
Thanks for your help!
